### ISSUE TITLE
Redirect to the same page after a Modal Pop-up Login

### ISSUE THREAD

**Issue by dbjpanda** [actions-pack/feedbacks#1]
To: support@dbjpanda.me
From: Antonio Graziano 

Hi, 

I write here as your support ask me in the chat. 

I've requested this feature: 

After a visitor makes the Login via Modal Pop-up Login, I would redirect him (as a subscriber or contributor) to the CURRENT PAGE where he has logged in via modal pop-up.

So, I need a redirect to a custom page, but the same he's looking at. 

This is because I want to sell different courses and User should login in before the purchase but I don't want to distract him. 

Your support answer me this: 
 This is currently not supported. But we are working on it as many of our clients have requested the same fearure. So give us some time. We will come back with the exact feature you want to see. 

I would like to know if you're working on this release and if there's a date for this. 

Thank you, 
Have a nice day.

**Comment by cornertip** [comment]
I' the original poster of this issue. 

The issue is solvable. 

**If you don't set any redirect** in the Modal Pop-up Login Form, the plugin works properly, so user can login and logout and it shows the same page he was visiting before the last action.
