### ISSUE TITLE
Feature Reequest: Action for editing profiles

### ISSUE THREAD

**Issue by olpo24** [actions-pack/feedbacks#10]

**Comment by olpo24** [comment]
Maybe with an option to upload an avatar/profile picture ;-)

**Comment by dbjpanda** [comment]
@olpo24 The feature you requested may take some time. Though we can't tell you the exact date. I think there are many free plugins that doe's the same 'frontend profile editing'.

**Comment by olpo24** [comment]
Thanks for reply. All plug-ins I found build a hole membership with registration sign in and all such stuff. Your solution is pretty lightweight ;-) -------- Ursprüngliche Nachricht --------Von: Dibyajyoti Panda <notifications@github.com>Datum: Do., 2. Jan. 2020, 15:17An: dbjpanda/actions-pack-issue-tracker <actions-pack-issue-tracker@noreply.github.com>Cc: olpo24 <o.poetter@gmx.de>, Mention <mention@noreply.github.com>Betreff: Re: [dbjpanda/actions-pack-issue-tracker] Feature Reequest: Action for editing profiles (#10)@olpo24 The feature you requested may take some time. Though we can't tell you the exact date. I think there are many free plugins that doe's the same 'frontend profile editing'.

**Comment by dbjpanda** [comment]
The feature was added in 2.0.1  https://actions-pack.com/changelog
