### ISSUE TITLE
[Action after submit issue] Email is sent also if the registered user/mail already exists

### ISSUE THREAD

**Issue by cornertip** [actions-pack/feedbacks#11]
Hi, 

after the new 1.2.9 release I encountered this error. I set a form with the following Actions After Submit: 

Register 
Email 1 to me
Email 2 to new registered user

Now, if you fill the form with an existing email or an existing user, the form displays the "username/mail already exists" error, BUT Email 1 and Email2 are triggered so that both me and user receive the registration confirmation emails, which is not correct as nobody should receive an email when this kind of error is displayed.

**Comment by dbjpanda** [comment]
@cornertip Are you adding an "Email" action along with "Register Action"?

**Comment by cornertip** [comment]
Hi @dbjpanda , 

yes, as I wrote above, I add "Email" and "Email2" with Register Action and bot emails are sent also if the email/username already exists and the error message is displayed above the registration form.

**Comment by dbjpanda** [comment]
An option to stop other actions when registration fails have been added in 2.0.9 https://actions-pack.com/changelog
