### ISSUE TITLE
How to add an extra user meta field in Elementor User Registration form?

### ISSUE THREAD

**Issue by dbjpanda** [actions-pack/feedbacks#2]
Given below a list of all available user meta keys. You just have to map your form field to those meta keys.

```
first_name
last_name
nickname
description
rich_editing
comment_shortcuts
admin_color
jabber
aim
yim
default_password_nag
use_ssl
show_admin_bar_front
show_welcome_panel
dismissed_wp_pointers
nav_menu_recently_edited
managenav-menuscolumnshidden
closedpostboxes_{post, dashboard, page, ...}
metaboxhidden_{post, dashboard, page,  ...}
meta-box-order_{post, dashboard, page,  ...}
screen_layout_{post, dashboard, page, ...}
and the following user meta keys that have the default table prefix:

wp_capabilities
wp_user_level
wp_dashboard_quick_press_last_post_id
wp_user-settings
wp_user-settings-time
```

Example

![Screenshot 2019-12-07 at 4 29 13 AM](https://user-images.githubusercontent.com/17483092/70362256-5652df00-18aa-11ea-8d22-0d34bba412dd.png)
![Screenshot 2019-12-07 at 4 29 20 AM](https://user-images.githubusercontent.com/17483092/70362261-5c48c000-18aa-11ea-8f88-a8b683023b05.png)

Output in Backend
![Screenshot 2019-12-07 at 4 28 50 AM](https://user-images.githubusercontent.com/17483092/70362264-6074dd80-18aa-11ea-8d6b-9cd0ae419442.png)

**Comment by mathevka** [comment]
Hello,
just working with your helpfull plugin. 
FOR REGISTRATION:
Is there a way to send the data, the new user filled in the form to send with the first registration-message to the new user.

Lets say sth like this:

Dear First-Name Last_Name,
we are proud to wellcome you on board.
This is what you etered in the form-fields:
First Name: First_Name
Last Name: Last_Name
Company Name: Company_Name
User Name: User_Name
Email: email
Password: password

please klick on the link to veryfie your registration....

and so on...


Thank you

**Comment by dbjpanda** [comment]
Hi, @mathevka please create separate github issue for separate support question. 
Create a new issue here https://github.com/dbjpanda/actions-pack-issue-tracker/issues/new  and copy paste your comment there.

**Comment by dbjpanda** [comment]
If you want to update **Name**  column in wordpress user table, you have to map both **first_name** and **last_name**

**Comment by dbjpanda** [comment]
More Examples
<img width="288" alt="Screenshot 2020-04-02 at 5 33 43 AM" src="https://user-images.githubusercontent.com/17483092/78197657-9e25f380-74a3-11ea-8267-2e8ef5fc6a02.png">
<img width="1164" alt="Screenshot 2020-04-02 at 5 34 02 AM" src="https://user-images.githubusercontent.com/17483092/78197661-a0884d80-74a3-11ea-8aff-33ed694185f9.png">

**Comment by GD-Simo** [comment]
Hello, how can I written on the original wp Name column?
