### ISSUE TITLE
Feature Request: Manual Account Activation

### ISSUE THREAD

**Issue by openmindeddrumming** [actions-pack/feedbacks#34]
Ability to manually activate the account by admin for current users.

**Comment by openmindeddrumming** [comment]
Hi there, I just wanted to mention, regarding the closest update to consider the functionality of manual email verification by admin.

Just yesterday I had another instance where the customer for some reason couldn't verify his email even after using a regular login form etc. 
I'm assisting him but basically if a customer writes a question then being able to immediately verify his email and unlock his login would be be very important from the customer service point of view...

**Comment by openmindeddrumming** [comment]
I had another instance where a person registered on the website, and later was logged out or left the site but then when tried to login again, he couldn't... again the user hasn't been verified. I directed that person to the regular wp-login and he managed to verify his email and was back in. 
Again just to support the manual email verification by admin functionality request, so I such cases we could quickly help users, especially when they purchase a product on the site :) :)

**Comment by dbjpanda** [comment]
@openmindeddrumming  Can you paste your Registration and Login Link please?

**Comment by openmindeddrumming** [comment]
You can find both links here
Openmindeddrumming.com/sign-up


sob., 18 lip 2020, 22:08 użytkownik Dibyajyoti Panda <
notifications@github.com> napisał:

**Comment by dbjpanda** [comment]
<img width="350" alt="Screenshot 2020-10-29 at 10 56 18 PM" src="https://user-images.githubusercontent.com/17483092/97609718-f7560580-1a39-11eb-838f-855e6937df90.png">

A force verification option has been added inside edit profile page.

**Comment by openmindeddrumming** [comment]
Great everything works perfect! Thank you, worth waiting! 
Waiting for more cool updates!
