### ISSUE TITLE
Use a custom meta field as a dynamic link

### ISSUE THREAD

**Issue by SeliemAttia** [actions-pack/feedbacks#41]
As we already discussed in the chat, I would like to have the option to use a custom meta field as a dynamic link. 

So the user can safe multiple links in different custom metas (Facebook, Instagram, Website...). Then I use a author archive template to show all kind of user information. I can only use titles tho. What I want to do is create a button with Elementor and use the value of a custom meta field as a dynamic link for the button. 

![Button Screenshot](https://user-images.githubusercontent.com/72135499/94679191-fab57e80-031f-11eb-984a-927f4430523c.png)

As shown in this image it is possible with the ACF Plugin to do it.

Ideally you would add this option for URLs but also for phone numbers and emails. So if I select a custom meta field as a dynamic link, I could choose if the value is a url, phonenumber or email adress and the browser would act accordingly.

**Comment by dbjpanda** [comment]
@SeliemAttia As you said, it is possible to do with ACF plugin currently. So do you think it is worthy to add the same feature again?

**Comment by SeliemAttia** [comment]
@dbjpanda 
Is it possible to connect the two of them? Or how is that supposed to help? 
I can't choose the profile Meta (made with your plugin) as a dynamic link when I use the ACF-danymic-Link.

**Comment by dbjpanda** [comment]
The feature had been added in version 2.3.3 https://actions-pack.com/changelog
<img width="325" alt="Screenshot 2020-10-29 at 10 51 48 PM" src="https://user-images.githubusercontent.com/17483092/97609221-56ffe100-1a39-11eb-8abd-a307e521b2d5.png">
