### ISSUE TITLE
Use a dynamic picture, which is not the profile picture.

### ISSUE THREAD

**Issue by SeliemAttia** [actions-pack/feedbacks#42]
I would love to give the user the option, to add another picture to his profile. 
I see that it is already possible to put a picture in the custom meta field. But I can't retrieve it using the image widget. 
![Bildschirmfoto 2020-09-30 um 13 30 51](https://user-images.githubusercontent.com/72135499/94679921-2f760580-0321-11eb-9191-2a09d052c6eb.png)

Only the profile picture can be shown and that is in a weird wordpress-format.
Please add the option so a profile can be connected to as many pictures as I want.

**Comment by dbjpanda** [comment]
The feature has been added in version 2.3.3 https://actions-pack.com/changelog

<img width="317" alt="Screenshot 2020-10-29 at 10 46 46 PM" src="https://user-images.githubusercontent.com/17483092/97608664-a2fe5600-1a38-11eb-8e19-b909877bfa60.png">
