### ISSUE TITLE
Locale language .mo not loaded 

### ISSUE THREAD

**Issue by joergen-n** [actions-pack/feedbacks#45]
I did a translation to danish - but the locale is not loaded.
Looked into the code in plugin.php. The path is defined by AP_PLUGIN_DIR_PATH.
I used the follwing code to check the path

function debug_load_textdomain( $domain , $mofile  ){
    error_log($domain . ', ' . $mofile);
}
add_action('load_textdomain','debug_load_textdomain', 10, 2);

That gave me this:
actions-pack, /var/www/html/wp-content/plugins/var/www/html/banner/wp-content/plugins/actions-pack-premium/languages/actions-pack-da_DK.mo

I changed the code to this:
load_plugin_textdomain( 'actions-pack', false, **dirname( plugin_basename( __FILE__ ) )  . '/languages/'** );

Now the locale is loaded.

**Comment by dbjpanda** [comment]
The issue has been fixed. https://actions-pack.com/changelog
