### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by whitinjl** [actions-pack/feedbacks#65]
I have downloaded the file actions-pack-premium-latest.zip and tried to upload it. Once I hit "Install Now" in Edge the page crashes after a wait with "Hmmm.....can't reach this page" and in Firefox I get the "wait dots" and then then the page stays the same with the same "Install Now" button" shown. 
Looking at the installed plugins, Action Packs does not appear.
My website url is www.baso.uk which is a valid url but is not recognized by your contact form. In fact, your contact form is not recognizing any valid url. I have no other way to raise this issue. I suspect this may be an issue with your website / validation

**Comment by dbjpanda** [comment]
Hi, 

Please send an email to support@actions-pack.com

Thank you
