### ISSUE TITLE
Profile picture 

### ISSUE THREAD

**Issue by Massive-Thebighead** [actions-pack/feedbacks#66]
I have created a field for profile picture upload on my signup form, How do I map it to display as profile picture.. Because currently, it doesn't display

**Comment by dbjpanda** [comment]
**Step-1**
You can create a custom meta as shown in the image below using Edit Profile Action

<img width="606" alt="Screenshot 2021-09-11 at 9 09 15 PM" src="https://user-images.githubusercontent.com/17483092/132953327-005149b4-31a3-4657-a20e-d18b57e786b6.png">

**Step-2**
If you want to make a public page for each user. You need to enable Author Archive and create an Elementor template for Author Archive. In the Author Archive template you can drag and drop an Image widget and select Dynamic and then select **Image Meta** and put the custom meta that you created in first step as shown in image below.

<img width="756" alt="Screenshot 2021-09-11 at 10 52 29 PM" src="https://user-images.githubusercontent.com/17483092/132956029-c3b5728f-c5a8-494d-9523-be1b3813ccc5.png">

**Step-3**
Now you can access every user's Profile by visiting **yoursite.com/author/username**
