### ISSUE TITLE
Actions Pack Premium Plugin Breaks WP-Admin login when activated

### ISSUE THREAD

**Issue by mmurillo66** [actions-pack/feedbacks#67]
I am running a wordpress site with Elementor Pro and the Hello Elementor Theme. Nothing unusual with my setup, all plugins except Elementor Pro have been deactivated and with Actions Pack Premium activated, I cannot login to the admin portal due to too many redirects!? I'm not sure why I'm getting this error. As soon as I deactivate the Action Pack plugin, I can login as normal. I have replicated this issue on different computers, in different networks, with different browsers. This plugin does not work for me for some reason.

**Comment by dbjpanda** [comment]
Hi, kindly send an email to support@actions-pack.com
