### ISSUE TITLE
Server error ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by eliranyaakov** [actions-pack/feedbacks#79]
I am running a wordpress site with Elementor Pro and the Hello Elementor Theme. Nothing unusual with my setup, all plugins except Elementor Pro have been deactivated and with Actions Pack Premium activated, I cannot login to the admin portal due to too many redirects!? I'm not sure why I'm getting this error. As soon as I deactivate the Action Pack plugin, I can login as normal. I have replicated this issue on different computers, in different networks, with different browsers. This plugin does not work for me for some reason.

**Comment by dbjpanda** [comment]
Hi @eliranyaakov there may be a multiple reason for the redirection loop. 4 primary steps to be taken, 
1st - Clear both server and browser cache
2nd -  Resave the permalink
3rd - Go to settings - General - Site Address - make sure you have put your https version of the site.
4th - Make sure you have put the right address here Login Action -> Additional Setting -> URL to Redirect Default Login Page

<img width="269" alt="Screenshot 2023-12-29 at 11 49 24 PM" src="https://github.com/actions-pack/feedbacks/assets/17483092/d27cf6e9-6c79-4c4c-b56e-50a43619edb7">
